### ISSUE TITLE
NullPointerException when clustering in Brazilian

### ISSUE THREAD

**Issue by stanislawosinski** [carrot2/carrot2#152]
When choosing the Brazilian clustering language, I get a NPE like this:

```
java.lang.NullPointerException
	at org.carrot2.language.extras.BrazilianLanguageComponents$BrazilianStemmerAdapter.stems(BrazilianLanguageComponents.java:44)
	at org.carrot2.language.extras.LuceneStemmerAdapter.stem(LuceneStemmerAdapter.java:45)
	at org.carrot2.text.preprocessing.LanguageModelStemmer.stem(LanguageModelStemmer.java:62)
	at org.carrot2.text.preprocessing.CompletePreprocessingPipeline.preprocess(CompletePreprocessingPipeline.java:102)
	at org.carrot2.clustering.lingo.LingoClusteringAlgorithm.cluster(LingoClusteringAlgorithm.java:167)
	at org.carrot2.dcs.servlets.ClusterServlet.runClustering(ClusterServlet.java:205)
        ...
```

**Comment by dweiss** [comment]
It is a bug. The returned stem can be null and the code does not take care
of this. I will review this here and in other places.

**Comment by dweiss** [comment]
This affects the Brazilian stemmer only. I pushed a fix.

**Comment by raffbr2** [comment]
Hello. Is it in prod? Can I download the new version and use it? Thanks

**Comment by stanislawosinski** [comment]
The fix is not yet officially released, here's a build with the fix: https://github.com/carrot2/carrot2/suites/7404441735/artifacts/301839828.

**Comment by raffbr2** [comment]
I tested here and the bug remains
<img width="882" alt="image" src="https://user-images.githubusercontent.com/8890639/179801530-b18ffe45-a63d-4e9c-a23c-79da66026714.png">

**Comment by dweiss** [comment]
@raffbr2 ? Can you check and confirm whether you're using the right nightly build?
